before_script:
#- export DB_ADDRESS=mongo
#- export DB_PORT=27017
image:   maven:latest

stages:
- build
- test-server
- test-client
- code-analysis

build:
  stage: build
  script:
  - mvn package -Dmaven.test.skip=true

test-server:
  services:
  - mongo:latest
  stage: test-server
  script:
  - cd server; mvn test

test-client:
    services:
    - mongo:latest
    stage: test-client
    script:
    - cd client; mvn test


checkstyle:
  stage: code-analysis
  script:
  - mvn  post-site
  allow_failure: true
