image: maven:latest
       mongo:latest
stages:
- build
- test
- code-analysis

build:
  stage: build
  script:
  - echo "Building"
  - mkdir build
  - touch build/info.txt
  artifacts:
    paths:
    - build/

test:
  services:
  - mongo:latest
  stage: test
  script:
  - mvn test


checkstyle:
  stage: code-analysis
  script:
  - mvn  post-site
  allow_failure: true
