before_script:
  - base64 /dev/urandom | head -c 256 > key
cache:
  paths:
  - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  DB_ADDRESS: "mongo"
  DB_PORT: "27017"

image:   maven:latest

stages:
- build
- test-server
- test-client
- code-analysis

build:
  stage: build
  script:
  - mvn clean install -Dmaven.test.skip=true

test-server:
  services:
  - mongo:latest
  stage: test-server
  script:
  - cd server; mvn test

test-client:
    services:
    - mongo:latest
    stage: test-client
    script:
    - cd client; mvn test


checkstyle:
  stage: code-analysis
  script:
  - mvn  checkstyle:check
