cache:
  paths:
  - .m2/repository/

build:
  stage: build
  script:
  - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS test
  - cat target/site/jacoco/index.html
  artifacts:
    paths:
    - target/site/jacoco/
pages:
  stage: deploy
  dependencies:
  - test
  script:
  - mkdir public
  - mv target/site/jacoco/index.html public
  artifacts:
    paths:
    - public

deploy:
  stage: deploy
  script:
  - mvn $MAVEN_CLI_OPTS verify
  only:
  - master