before_script:
- export DB_ADDRESS=mongo
- export DB_PORT=27017
image:   maven:latest

stages:
- build
- test
- code-analysis

build:
  stage: build
  script:
  - mvn package -Dmaven.test.skip=true

test:
  services:
  - mongo:latest
  stage: test
  script:
  - mvn test


checkstyle:
  stage: code-analysis
  script:
  - mvn  post-site
  allow_failure: true
