image: maven:latest
stages:
    - build
    - test
    - code-analysis

build:
    stage: build
    script:
    - echo "Building"
    - mkdir build
    - touch build/info.txt
    artifacts:
      paths:
      - build/

test:
    stage: test
    script:
    - mvn  test -f "./server/pom.xml"
    - mvn  test -f "./client/pom.xml"


checkstyle:
    stage: code-analysis
    script:
    - mvn  post-site -f "./client/pom.xml"
    - mvn  post-site -f "./server/pom.xml"
    allow_failure: true
